name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v10

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build flake
        run: nix flake check

      - name: Check formatting
        run: nix develop --command cargo fmt --all -- --check

      - name: Lint
        run: nix develop --command cargo clippy -- -D warnings

      - name: Test
        run: nix develop --command cargo nextest run
