name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v10

      - uses: cachix/cachix-action@v16
        with:
          name: bongo-modulator
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run flake checks
        run: nix flake check

      - name: Build package
        # Build the main bongo-modulator derivation
        run: nix build .#packages.x86_64-linux.default

      - name: Check formatting
        run: nix develop --command cargo fmt --all -- --check

      - name: Lint
        run: |
          nix build --out-link result-clippy .#clippyCheck
          cachix push bongo-modulator result-clippy

      - name: Test
        run: |
          nix build --out-link result-nextest .#nextestCheck
          cachix push bongo-modulator result-nextest
